version: "3"
services:
  app:
    image: xdman/gui:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - $PWD/downloads:/root/Downloads
    network_mode: host
